// typedef struct {...} Result;
// #RESULT_ERR(obj, idx, err)
// #RESULT_OK(obj, idx)
// #COMMENT
// _swz_parse_obj_[internal|helper](...)
// _swz_parse_[integer|number](...)
// _skip_space_and_comments(...)
// _swz_escape(...)
// _swz_parse_string(...)
// _swz_parse_list_or_sexpr(...)
// _split_symbol(...)
// _swz_parse_symbol(...)
// _swz_parse_quote(...)
// _swz_parse_obj_[internal|helper](...)
// _set_error_lineno(...)
// _read_file(...)
// swz_parse_obj(...)
// swz_parse_progn(...)
// swz_parse_progn_f()
// swz_load_file(...)